eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

server:
  port: 9999

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

  # Redis Configuration
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: qwer

  # Auto Create Gateway Routes from Eureka Service Registry
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          httpclient:
            connect-timeout: 1000
            response-timeout: 5s

          # Load Balancer and route Configuration
          routes:
            # Account Service Route with Circuit Breaker
            - id: account
              uri: lb://account
              predicates:
              - Path=/account/**
              filters:
              - RewritePath=/account/(?<segment>.*), /$\{segment}
#              - name: RequestRateLimiter
#                args:
#                  redis-rate-limiter.replenishRate: 2
#                  redis-rate-limiter.burstCapacity: 5
#                  redis-rate-limiter.requestedTokens: 1
#                  key-resolver: "#{@userKeyResolver}"

            # Pipeline Service Route with Circuit Breaker
            - id: pipeline
              uri: lb://pipeline
              predicates:
                - Path=/pipeline/**
              filters:
                - RewritePath=/pipeline/(?<segment>.*), /$\{segment}
#                - name: RequestRateLimiter
#                  args:
#                    redis-rate-limiter.replenishRate: 10
#                    redis-rate-limiter.burstCapacity: 20
#                    redis-rate-limiter.requestedTokens: 1


# Retry Filter        Example
#                - name: Retry
#                  args:
#                    retries: 5
#                    statuses: BAD_GATEWAY
#                    methods: GET
#                    backoff:
#                      firstBackoff: 10ms
#                      maxBackoff: 50ms
#                      factor: 2
#                      basedOnPreviousValue: false


# # Circuit Breaker Filter        Example
#                - name: CircuitBreaker
#                  args:
#                    name: pipelineCircuitBreaker
#                    fallbackUri: forward:/fallback/pipeline/api/v1/accounts

  # Configure OAuth2 Client for Gateway Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type: authorization_code
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50 # Percentage
        permitted-number-of-calls-in-half-open-state: 1 # this mean that we need to have 2 successful calls to close the circuit
        wait-duration-in-open-state: 10000 #

# For Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
