server:
  port: 8888

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

spring:
  application:
    name: configserver
  profiles:
    active: git,dev,vault # native, vault

  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          kv-version: 2
          backend: secret
          profile-separator: /
        git:
          uri: ${GL_URI}
          username: ${GL_USERNAME}
          password: ${GL_TOKEN}
          default-label: main
          search-paths: "/**"
        native:
          search-locations:
           -  file:/home/tong-bora/source-code/spring-boot/ISTAD/itp-config-repo/{application}/
           -  file:/home/tong-bora/source-code/spring-boot/ISTAD/itp-config-repo/

