eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

server:
  port: 20262

spring:
  application:
    name: pipeline
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    # Auto Create Gateway Routes from Eureka Service Registry
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

    # Configure Spring Cloud Stream with Kafka Binder
    # Defines three function beans that Spring Cloud Stream will bind to messaging channels
    # These functions should exist as @Bean methods in Spring application
    function:
      definition: processProduct;processMessage;processProductDetail
    stream:
      bindings:
        processProduct-in-0:
          destination: test-product # Kafka topic that this function will consume from
          group: monitor-group # consumer_group_id
          content-type: application/json
        processMessage-in-0:
          destination: test-topic # Kafka topic that this function will consume from
        processProductDetail-in-0:
          destination: product-detail # Kafka topic that this function will consume from
          group: monitor-group2 # consumer_group_id
          content-type: application/json
        processProductDetail-out-0:
          destination: processed-product-detail # Kafka topic that this function will produce to
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:29092,localhost:29094,localhost:29096
          configuration:
            auto.offset.reset: earliest


  # Configure OAuth2 Client for Gateway Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
      client:
        provider:
          itp-standard:
            issuer-uri: http://localhost:9090
        registration:
          itp-standard:
            provider: itp-standard
            client-id: itp-standard
            client-secret: qwerqwer
            redirect-uri: http://localhost:9999/login/oauth2/code/itp-standard
            authorization-grant-type: client_credentials
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50 # Percentage
        permitted-number-of-calls-in-half-open-state: 2 # this mean that we need to have 2 successful calls to close the circuit
        wait-duration-in-open-state: 10000 #
#    instances:
#      accountCircuitBreaker:
#        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.tongbora.pipelineservice: DEBUG